### ISSUE TITLE
Please make formal release

### ISSUE THREAD

**Issue by jonassmedegaard** [ganaware/pcf2bdf#1]
Please issue a formal release to include the changes made in 2012.

**Comment by ganaware** [comment]
OK, I'll release it soon.

**Comment by ganaware** [comment]
I released 1.05.
Any problem?

**Comment by jonassmedegaard** [comment]
Quoting ganaware (2015-05-18 04:59:15)

> I released 1.05.
> Any problem?

Thanks!

No, no problems: Now packaged officially for Debian: 
https://packages.qa.debian.org/p/pcf2bdf.html

(should appear at above URL within few minutes)
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by ganaware** [comment]
> No, no problems: Now packaged officially for Debian:
> https://packages.qa.debian.org/p/pcf2bdf.html

Thanks!
